# Generated by Django 4.0.3 on 2022-09-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmsapp', '0002_series60'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series60',
            name='id',
        ),
        migrations.AlterField(
            model_name='series60',
            name='skfNo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
