# Generated by Django 4.0.3 on 2022-09-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmsapp', '0003_remove_series60_id_alter_series60_skfno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='aload',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='userip',
            name='dia',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userip',
            name='elife',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='userip',
            name='lfactor',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='userip',
            name='rload',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='userip',
            name='rpm',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
