# Generated by Django 4.0.3 on 2022-09-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmsapp', '0007_eqbload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqbload',
            name='e',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='eqbload',
            name='faco',
            field=models.DecimalField(decimal_places=3, max_digits=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eqbload',
            name='gx',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='eqbload',
            name='gy',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='eqbload',
            name='lx',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='eqbload',
            name='ly',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
