# Generated by Django 4.0.3 on 2022-10-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmsapp', '0008_alter_eqbload_e_alter_eqbload_faco_alter_eqbload_gx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='series65',
            fields=[
                ('skfNo', models.IntegerField(primary_key=True, serialize=False)),
                ('dia', models.IntegerField()),
                ('d1min', models.IntegerField()),
                ('dcap', models.IntegerField()),
                ('d2min', models.IntegerField()),
                ('bB', models.IntegerField()),
                ('rR', models.IntegerField()),
                ('rR1', models.IntegerField()),
                ('staticC', models.IntegerField()),
                ('dynamicC', models.IntegerField()),
                ('maxSpeed', models.IntegerField()),
            ],
        ),
    ]
